// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	queue "github.com/splunk/kafka-mq-go/queue"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetOrCreateQueue provides a mock function with given fields: id
func (_m *Service) GetOrCreateQueue(id string) queue.Queue {
	ret := _m.Called(id)

	var r0 queue.Queue
	if rf, ok := ret.Get(0).(func(string) queue.Queue); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queue.Queue)
		}
	}

	return r0
}
