// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MarkerConsumer is an autogenerated mock type for the MarkerConsumer type
type MarkerConsumer struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *MarkerConsumer) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *MarkerConsumer) Stop() {
	_m.Called()
}
